### ISSUE TITLE
Pair of methylation calls without any strand information

### ISSUE THREAD

**Issue by onurcanbektas** [cxzhu/SIMPLE-seq#5]
In the final data for 5mC, we see pairs of methylation calls without any strand information. Is this supposed to happen? If so, how can we filter out methylation calls coming from one of the stands.
<img width="469" alt="Clipboard - June 19, 2024 10_51" src="https://github.com/cxzhu/SIMPLE-seq/assets/18240112/965bad88-72e3-442a-a188-f7d311279a42">

**Comment by cxzhu** [comment]
Hi @onurcanbektas, if I understand your question correctly: the methylation call from a "C" base is on the top strand and the methylation call from a "G" base is from the bottom strand.

**Comment by onurcanbektas** [comment]
yes, but how can we determine which methylation call is from which strand? 
Clearly there are rows where one strand is methylated and the other is not.

**Comment by cxzhu** [comment]
For the analyses presented in our publication, there is no need to split strand calls. The rationale is that the chance of capturing two strands for one loci in a given cell is extremely low (<0.1%). However, if the strand information is useful for you, you can always retreive this from BAM files.

**Comment by onurcanbektas** [comment]
Dear @cxzhu , in the above case, why do we always see pairs of consequitive methylation information? 
Assuming these consequitive information are just redundancy from the sequencing, how should we determine the methylation call at position 246039 and 246040, given that the former is methylated and the latter is not?

**Comment by cxzhu** [comment]
> Dear @cxzhu , in the above case, why do we always see pairs of consequitive methylation information? Assuming these consequitive information are just redundancy from the sequencing, how should we determine the methylation call at position 246039 and 246040, given that the former is methylated and the latter is not?

Dear @onurcanbektas, in mammalian genome, 5mC are typically in CpG dinucleotides.

In this case, 246039 is C and 246040 is G. The 246039 is called as 5mC as the upper strand is detected. For 246040, no "G-to-A" was detected, possible reasons are: (1) the bottom strand was not captured, or (2) the bottom strand is not methylated (hemi-methylated).

**Comment by onurcanbektas** [comment]
@cxzhu thank you very much!

**Comment by onurcanbektas** [comment]
I'm sorry for asking this many questions. 
You said it is highly unlikely for two strands to be captured at the same loci, yet in the data we see such consequitive CpG position extremely often (both in methylated and unmethylated form) when we process it. Do you think we did something wrong and have I misunderstood something?

> For the analyses presented in our publication, there is no need to split strand calls. The rationale is that the chance of capturing two strands for one loci in a given cell is extremely low (<0.1%). However, if the strand information is useful for you, you can always retreive this from BAM files.

**Comment by cxzhu** [comment]
@onurcanbektas , from the methylation table here, ie., 246039 and 40, what we can be sure is that we detected the upper strand, but cannot know whether the bottom strand is detected. On the other hand, if we see a 0 and 1 for another CpG, that means we detected the bottom strand, but not sure if captured the upper stand. The only situation that we know two strands are captured if we have 1 and 1 for both C and G.

**Comment by onurcanbektas** [comment]
So if I understood correctly, the fact that we have the position 246040 in the data doesn't mean we have detected any reads from that position?

**Comment by cxzhu** [comment]
If doesn't detect the reads from the bottom strand. But it’s a G in the upper strand.

Best,
Chenxu

On Jan 14, 2025, at 10:06, onurcanbektas ***@***.***> wrote:


ⓘ Informational: External Sender
This sender is external to Weill Cornell Medicine. Be careful when clicking links or opening attachments.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/Aer6R9v1Nk4!Ni0UnVd53v2OWN7ZN9jiH4idRuYzjFfLyN6P1PUcI3lwhMVmTZwJPehBXTsxB7FaI3eC7SDFaS-JNVu9gHuqozKi6KTvQLnqwPKjhnqm1zI$>
Report Suspicious


So if I understood correctly, the fact that we have the position 246040 in the data doesn't mean we have detected any reads from that position?

**Comment by onurcanbektas** [comment]
@cxzhu I'm not sure I understood what you mean by your last message. Would you mind elaborating a bit more?

**Comment by cxzhu** [comment]
The position 40 is the combined ratio of upper stand G and bottom strand C. However, if the depth is only 1, then yes, we only detected the upper strand because 39 is mutated and must be the upper strand 5mC. If the depth is >=2 and detected a “C-to-T” at 39, but did not detect “G-to-A” at 40, this could be two situations: (1) captured 1 upper strand 5mC-G read and 1 bottom strand G-C read, or captured 2 upper stand reads + 0 bottom strand reads. I hope this explanation can be helpful.

Best,
Chenxu

On Jan 14, 2025, at 10:21, onurcanbektas ***@***.***> wrote:


ⓘ Informational: External Sender
This sender is external to Weill Cornell Medicine. Be careful when clicking links or opening attachments.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/Aer6R9v1Nk4!Ni0UnVd53v2OWN7ZN9jiH4idRuYzjFfLyN6P1PUcI3lw5GWmzd2pPehBXTsxB7FawNIcI8Af5tk6AyCQTVEjFPi_jqEToBnH_PPp_EmgMSo$>
Report Suspicious


@cxzhu<https://urldefense.com/v3/__https://github.com/cxzhu__;!!Aer6R9v1Nk4!-w3kOqdBhD4c4YFBlM_A5L5lwsxggudkWUhN6uZxt0Jy_G35fDm2CRTkaWEeyM5msoX_2WdfmfrDiUX3-KgbhP5xCFNPWLzJpw$> I'm not sure I understood what you mean by your last message. Would you mind elaborating a bit more?
